### ISSUE TITLE
Handle user information more effectively

### ISSUE THREAD

**Issue by landoskape** [landoskape/networkAlignmentAnalysis#20]
As it is, the only user information retrieved from ``files`` is the ``base_path`` for each user. However, different kinds of basepaths require different behavior (in particular the local vs remote cluster paths). 

It would probably be smarter to keep more information than the ``base_path`` in the user registry like what kind of computer it is, etc., then use that information accordingly throughout the code.

**Comment by celiaberon** [comment]
Could use a slurm environment variable to set a flag somewhere that a job is running on the cluster, and use that to control  paths, etc. Have been using this in parts of the code, but we just use it most upstream to set some configuration?
